"""initial migration

Revision ID: d5c4b7847587
Revises: 4e7844179b4e
Create Date: 2024-08-28 15:02:54.687008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c4b7847587'
down_revision = '4e7844179b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
